# This workflow will do a clean install of node dependencies, run the linter and tests on Node 14.x

name: Camping React Native APP Build and Test CI

on:
  push:
    branches: [ feature/**, fix/** ]

jobs:
  test:
    name: Build and test React APP
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn install
    - name: Copy .env.dist to .env
      run: cp .env.dist .env
    - name: Run the linter
      run: yarn lint
    - name: Run the tests
      run: yarn test
